---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: ap-northeast-1
  version: "1.15"
  tags:
    env: test

iam:
  withOIDC: true

vpc:
  subnets:
    public:
      ap-northeast-1a: { id: subnet-id }
      ap-northeast-1c: { id: subnet-id }
      ap-northeast-1d: { id: subnet-id }
    private:
      ap-northeast-1a: { id: subnet-id }
      ap-northeast-1c: { id: subnet-id }
      ap-northeast-1d: { id: subnet-id }

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
