---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: ap-northeast-1
  version: "1.15"
  tags:
    env: test

managedNodeGroups:
  - name: test-maneged-ng
    desiredCapacity: 3
    minSize: 2
    maxSize: 4
    instanceType: t3.large
    volumeSize: 20
    ssh:
      allow: true
    privateNetworking: true
    iam:
      instanceRoleARN: <your-role>
